version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    dockerr:
      - image: cimg/node:16.4.0
    steps:
      - checkout
      - run:
        name: install dependency
        command: npm install
      - run: 
        name: Run Tests
        command: npm run test
      -run: node --version
